name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build UI
        working-directory: ui
        run: npm ci && npm run build

      - name: Ensure Maven wrapper is executable
        run: chmod +x mvnw

      - name: Build and test with Maven
        run: ./mvnw -B -ntp clean verify
