name: Build

on:
  push:
    branches:
      - main
      - pivot/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      # Set up JDK for backend build
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build backend with Maven
        run: mvn -B clean verify

      # Set up Node for frontend build
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ui-react/package-lock.json

      - name: Install frontend deps
        run: npm ci --prefix ui-react

      - name: Build frontend
        run: npm run build --prefix ui-react 